<?php
    $livros = [
        ['id' => 1, 'titulo' => 'Jogos Vorazes', 'autor' => 'Suzanne Collins', 'descricao' => 'Constituída por uma suntuosa Capital cercada de 12 distritos periféricos, a nação de Panem se ergueu após a destruição dos Estados Unidos. Como represália por um levante contra a capital, a cada ano os distritos são forçados a enviar um menino e uma menina entre 12 e 18 anos para participar dos Jogos Vorazes.'],
        ['id' => 2, 'titulo' => 'Talvez você deva conversar com alguém', 'autor' => 'Lori Gottlieb', 'descricao' => 'De modo geral, buscamos a ajuda de um terapeuta para melhor compreender as angústias, os medos, a culpa ou quaisquer outros sentimentos que nos causam desconforto e sofrimento. Mas quantos de nós já paramos para perguntar: o terapeuta está imune à gama de questões que ele auxilia seus pacientes a dirimir e superar, dia após dia?'],
        ['id' => 3, 'titulo' => 'É assim que se perde a guerra do tempo', 'autor' => 'Amal El-Mohtar', 'descricao' => 'Entre as cinzas de um mundo em ruínas, uma soldada encontra uma carta que diz: Queime antes de ler. E assim tem início uma correspondência improvável entre duas agentes de facções rivais travando uma guerra através do tempo e espaço para assegurar o melhor futuro para seus respectivos times. E então, o que começa como uma provocação se transforma em algo mais.'],
        ['id' => 4, 'titulo' => 'O Mundo Sem Anéis', 'autor' => 'Mariana Bertol Carpanezzi', 'descricao' => '"O mundo sem anéis" não é um livro de viagens tradicional. Em vez de casos anedóticos e descrições de paisagem, o que o leitor encontra nas páginas é uma jornada de descobertas pessoais e insights da autora, que pedalou sozinha durante 100 dias pela França, Espanha e Portugal.'],
        ['id' => 5, 'titulo' => 'Vamos Comprar Um Poeta', 'autor' => 'Afonso Cruz', 'descricao' => 'Numa sociedade dominada pelo materialismo, as famílias têm artistas em vez de animais de estimação. É nesse cenário, onde cada espaço tem um patrocinador, cada passo é medido com exatidão, e até a troca dos afetos é contabilizada, que uma menina pede ao pai um poeta.'],
        ['id' => 6, 'titulo' => 'Kim Jiyoung, nascida em 1982', 'autor' => 'Cho Nam-Joo', 'descricao' => 'Com narrativa sutil e ao mesmo tempo arrebatadora, Kim Jiyoung, nascida em 1982 retrata a realidade de uma jovem coreana e os profundos impactos da desigualdade de gênero na vida das mulheres.'],
        ['id' => 7, 'titulo' => 'A biblioteca da meia-noite', 'autor' => 'Suzanne Collins', 'descricao' => 'A biblioteca da meia-noite é um romance incrível que fala dos infinitos rumos que a vida pode tomar e da busca incessante pelo rumo certo.'],
        ['id' => 8, 'titulo' => 'Se deus me chamar não vou', 'autor' => 'Mariana Salomão Carrara', 'descricao' => 'Quem vai te contar essa história é uma criança de 11 anos. O olhar fresco e bem humorado de quem ainda vê a vida como mistério está aqui, mas vá por mim: não subestime a solidão de Maria Carmem.'],
        ['id' => 9, 'titulo' => 'Rádio Silêncio', 'autor' => 'Alice Oseman', 'descricao' => 'Rádio Silêncio não é um livro leve e apresenta uma trama que prende o leitor até suas páginas finais. A história principal que envolve Frances e os gêmeos Last é acompanhada por dramas secundários que são tão envolventes quanto o cerne principal desta narrativa.'],
        ['id' => 10, 'titulo' => 'Os sete maridos de Evelyn Hugo', 'autor' => 'Taylor Jenkins Reid', 'descricao' => 'Com todo o esplendor que só a Hollywood do século passado pode oferecer, esta é uma narrativa inesquecível sobre os sacrifícios que fazemos por amor, o perigo dos segredos e o preço da fama.'],
    ];
?>